### ISSUE TITLE
Introduce TCK as a CI test

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/ts-nats-template#11]
#### Reason/Context
Introduce the [TCK](https://github.com/asyncapi/tck) to ensure all valid AsyncAPI documents works as expected. i.e. can be generated and tests are succeeding.

#### Description
How this should be solved is up for discussion.

Depending on the time it takes to finish all the tests by the CI we might have to add a GH action which runs in the morning/evening each day and if any errors are found it should create a PR (if one not already exist) that a certain document are failing to be rendered. Maybe this can be used through all our repositories 🤔 ?

Blocked by:

- #10 
- #9

**Comment by magicmatatjahu** [comment]
@jonaslagoni It's still valid?

**Comment by jonaslagoni** [comment]
I am gonna close this issue down, even though somewhat still relevant. TCK needs to be adapted to support this, so for now, it is unreachable.
