### ISSUE TITLE
Move model generation to template

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/ts-nats-template#54]
#### Reason/Context
Questioned in this PR - https://github.com/asyncapi/ts-nats-template/pull/53 

Look into whether model generation should be moved from [this](https://github.com/asyncapi/ts-nats-template/blob/master/hooks/quicktype-schema.js) to a template file.

**Comment by magicmatatjahu** [comment]
This issue also is blocked by https://github.com/asyncapi/generator/issues/515
