### ISSUE TITLE
Move docs to template directory to remove the redundant hook

### ISSUE THREAD

**Issue by kaushik-rishi** [asyncapi/ts-nats-template#546]
#### Reason/Context
- As per my understanding all this hook is doing is copying the docs folder from the root directory into the generated output directory
- https://github.com/asyncapi/ts-nats-template/blob/master/hooks/copy-docs.js
- can we not just move the docs directory inside of template to have docs inside the template without using the hook ?

**Comment by jonaslagoni** [comment]
We could, but the docs are part of the template docs as well, which is why they are copied.

So I dont think this change makes sense 😄

**Comment by jonaslagoni** [comment]
Closing as above stands and no further discussion was engaged 🙂
