### ISSUE TITLE
Fix error handling 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/ts-nats-template#6]
#### Describe the bug
Currently we wrap internal (nats.ts library errors) in a custom `NatsTypescriptTemplateError`. However the stacktrace are lost in the tranformation when it shouldnt.

#### How to Reproduce
If any nats errors are thrown you can see the missing error stack trace.

#### Expected behavior
Should provide full error stack trace to where the original error was thrown.

**Comment by magicmatatjahu** [comment]
@jonaslagoni It's still valid?
