### ISSUE TITLE
migrate to nats.js

### ISSUE THREAD

**Issue by aricart** [asyncapi/ts-nats-template#84]
This library is depending on the ts-nats library which is now superseded by the async functionality of the nats.js library. 
There will be quite a few changes required but on the positive side the client code will be compatible/portable to other nats javascript platforms.

Please see https://github.com/nats-io/nats.js/blob/master/migration.md.

**Comment by jonaslagoni** [comment]
Thanks for raising the issue @aricart! 

Would you recommend switching now, even though it is still a release candidate?

**Comment by aricart** [comment]
@jonaslagoni yes you can start looking at it. Currently the active changes are jetstream related.
