### ISSUE TITLE
Generate tests for different payloads

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/ts-nats-template#9]
#### Reason/Context
At the moment the only tested functionality is the JSON payload. Binary and string should also be tested to ensure the functionality works.

#### Description
Add tests for each channel which tries different payloads.

**Comment by magicmatatjahu** [comment]
@jonaslagoni It's still valid?

**Comment by jonaslagoni** [comment]
Still relevant, after https://github.com/asyncapi/ts-nats-template/pull/391 it should be easier and make more sense to add.
